version: '3'
services:
  proxy:
    image: caddy:2.2.1-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site:/srv
      - caddy_config:/config
      - caddy_data:/data
     # - ./Caddyfile:/etc/caddy/Caddyfile    
      - ./caddy.json:/etc/caddy/caddy.json 
    command: caddy run --config /etc/caddy/caddy.json
    #if we use caddy.json then we need to use caddy run --config /etc/caddy/caddy.json
    if we use Caddyfile then not need to run cadd.json
    networks:
    - utags

networks:
  utags:
    name: utags
    external: true

volumes:
  caddy_data:
    external: true
  caddy_config:
