version: '3'
services:
  app:
    image: logicwind/utags-sumanth:dev
    container_name: app
    env_file:
      - .env
    #environment:
      #DB_HOST: host.docker.internal
    ports:
       # - "8080:80"
        - "3005:3005"
   # DATABASE_URL: postgres://root:root@13.233.69.101:5432/root
    networks:
      - utags

  ##  HELTHCHECK  ## 
  # app:
  #   image: nginx
  #   container_name: node
  #   ports:
  #     - "8080:80" 
    # healthcheck:
    #   test: 'curl -f http://localhost:80'
    #   interval: 2s
    #   retries: 5
    #   start_period: 1s
    #   timeout: 2s

networks:
  utags:
    name: utags
    external: true

