version: '3'
services:
  postgres:
    image: postgres:14.6
    container_name: postgres
    volumes:
      - data:/data/db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: utags_db
    ports:
      - "5432:5432"
    networks:
     - mynetwork

volumes:
  data:

networks:
  mynetwork:
    name: mynetwork
    external: true
